
class GuiErrorType:
    Gui_Err_AccessDenied = 633 # Acesso negado.
    Gui_Err_Bad_Focus = 634 # Não é possível definir o foco neste objeto.
    Gui_Err_Bad_Index_Type = 618 # Tipo de índice inválido para acesso à coleção.
    Gui_Err_Control_Label = 615 # O controle não pôde ser encontrado pelo rótulo.
    Gui_Err_Control_Name = 608 # O controle não pôde ser encontrado pelo nome.
    Gui_Err_Control_Position = 616 # O controle não pôde ser encontrado pela posição.
    Gui_Err_Disconnected = 621 # O objeto invocado se desconectou de seus clientes.
    Gui_Err_Enumerator_Index = 614 # O enumerador da coleção não pode encontrar um elemento com o índice especificado.
    Gui_Err_Enumerator_Reset = 612 # O enumerador da coleção não pode ser redefinido.
    Gui_Err_FindById = 619 # O controle não pôde ser encontrado pelo ID.
    Gui_Err_FindByName = 620 # O controle não pôde ser encontrado pelo nome.
    Gui_Err_FindByPos = 632 # O controle não pôde ser encontrado pela posição.
    Gui_Err_Front_Module = 602 # O caminho do 'sapfront.dll' não pôde ser determinado.
    Gui_Err_Init = 601 # O mecanismo do Sapgui não pode ser inicializado.
    Gui_Err_Int_Get_Session_Failed = 629 # Não é possível obter a sessão do TLS.
    Gui_Err_Int_GetCtrl_Failed = 625 # Não foi possível obter o controle (Erro interno).
    Gui_Err_Int_GetFocusManFromSes_Failed = 627 # Não foi possível obter o gerenciador de foco da sessão (Erro interno).
    Gui_Err_Int_GetSesFromCtrl_Failed = 626 # Não foi possível obter a sessão do controle (Erro interno).
    Gui_Err_Int_Invalid_TestToolMode = 628 # Modo de ferramenta de teste inválido.
    Gui_Err_Int_View_Not_Set = 630 # Visão não definida (Erro interno).
    Gui_Err_Invalid_Argument = 613 # O método recebeu um argumento inválido.
    Gui_Err_Invalid_Context = 603 # Função chamada em contexto de thread inválido.
    Gui_Err_Invalid_Window = 611 # A janela requerida é inválida.
    Gui_Err_Logon_Module = 604 # O 'Componente de Logon do Sapgui' não pôde ser instanciado.
    Gui_Err_Menu_Disabled = 623 # O item de menu está desativado.
    Gui_Err_No_Memory = 607 # O sistema está sem memória.
    Gui_Err_No_Wrapper = 622 # Nenhum wrapper disponível para este controle.
    Gui_Err_Not_Implemented = 610 # O método ou propriedade não está atualmente implementado.
    Gui_Err_Permission_Denied = 637 # Permissão negada.
    Gui_Err_Property_Readonly = 609 # A propriedade é somente leitura.
    Gui_Err_Resize_Failed = 631 # Falha ao redimensionar.
    Gui_Err_Sapgui_Module = 605 # O 'Componente Sapgui' não pôde ser instanciado.
    Gui_Err_Save_Image = 635 # Erro ao salvar a imagem.
    Gui_Err_Scripting_Disabled_Srv = 624 # O scripting está desativado pelo servidor.
    Gui_Err_Session_Index = 606 # O índice da sessão está fora de alcance.
    Gui_Err_Shortcut_Evaluation = 636 # Falha na avaliação do atalho.
    Gui_Err_SL_No_Entry = 1000 # Não é uma entrada válida do SAPLogon.
    Gui_Err_VKey_Disabled = 617 # A tecla virtual não está habilitada.
